import { NavigationConfig, WhatScienceMenuItem } from '@/types/navigation'

// Translation keys mapping
const navTranslations: Record<string, Record<string, string>> = {
  en: {
    'What science can do': 'What science can do',
    'Home': 'Home',
    'About Us': 'About Us',
    'Manufacturing': 'Manufacturing',
    'R&D Innovation': 'R&D Innovation',
    'Quality & Compliance': 'Quality & Compliance',
    'Products': 'Products',
    'News': 'News',
    'Careers': 'Careers',
    'Contact': 'Contact',
    'Resources': 'Resources',
    'Overview': 'Overview',
    'Stories of impact': 'Stories of impact',
    'Publications': 'Publications',
    'Softgels': 'Softgels',
    'Tablets': 'Tablets',
    'Creams & Ointments': 'Creams & Ointments',
    'Injections': 'Injections',
  },
  lo: {
    'What science can do': 'ສິ່່ງທີ່ເໝາະສົ້ມ',
    'Home': 'ໜ້າຫໍ່',
    'About Us': 'ກ່ຽວກ່ຽວກ໱ບ',
    'Manufacturing': 'ການ Manufacturing',
    'R&D Innovation': 'R&D Innovation',
    'Quality & Compliance': 'Quality & Compliance',
    'Products': 'Products',
    'News': 'News',
    'Careers': 'Careers',
    'Contact': 'Contact',
    'Resources': 'Resources',
    'Overview': 'Overview',
    'Stories of impact': 'Stories of impact',
    'Publications': 'Publications',
    'Softgels': 'Softgels',
    'Tablets': 'Tablets',
    'Creams & Ointments': 'Creams & Ointments',
    'Injections': 'Injections',
  },
  th: {
    'What science can do': 'What science can do',
    'Home': 'หน้าแรก',
    'About Us': 'เกี่ยวกับเรา',
    'Manufacturing': 'การผลิต',
    'R&D Innovation': 'R&D Innovation',
    'Quality & Compliance': 'Quality & Compliance',
    'Products': 'Products',
    'News': 'News',
    'Careers': 'Careers',
    'Contact': 'Contact',
    'Resources': 'Resources',
    'Overview': 'Overview',
    'Stories of impact': 'Stories of impact',
    'Publications': 'Publications',
    'Softgels': 'Softgels',
    'Tablets': 'Tablets',
    'Creams & Ointments': 'Creams & Ointments',
    'Injections': 'Injections',
  },
  vi: {
    'What science can do': 'What science can do',
    'Home': 'Trang chủ',
    'About Us': 'Giới thiệu',
    'Manufacturing': 'Sản xuất',
    'R&D Innovation': 'R&D Innovation',
    'Quality & Compliance': 'Quality & Compliance',
    'Products': 'Products',
    'News': 'News',
    'Careers': 'Careers',
    'Contact': 'Contact',
    'Resources': 'Resources',
    'Overview': 'Overview',
    'Stories of impact': 'Stories of impact',
    'Publications': 'Publications',
    'Softgels': 'Softgels',
    'Tablets': 'Tablets',
    'Creams & Ointments': 'Creams & Ointments',
    'Injections': 'Injections',
  },
  ar: {
    'What science can do': 'ما يمكن أن تفعله العلوم',
    'Home': 'الرئيسية',
    'About Us': 'من نحن',
    'Manufacturing': 'التصنيع',
    'R&D Innovation': 'R&D Innovation',
    'Quality & Compliance': 'Quality & Compliance',
    'Products': 'Products',
    'News': 'News',
    'Careers': 'Careers',
    'Contact': 'Contact',
    'Resources': 'Resources',
    'Overview': 'Overview',
    'Stories of impact': 'Stories of impact',
    'Publications': 'Publications',
    'Softgels': 'Softgels',
    'Tablets': 'Tablets',
    'Creams & Ointments': 'Creams & Ointments',
    'Injections': 'Injections',
  },
  es: {
    'What science can do': 'Lo que la ciencia puede hacer',
    'Home': 'Inicio',
    'About Us': 'Sobre nosotros',
    'Manufacturing': 'Fabricación',
    'R&D Innovation': 'R&D Innovation',
    'Quality & Compliance': 'Quality & Compliance',
    'Products': 'Products',
    'News': 'News',
    'Careers': 'Careers',
    'Contact': 'Contact',
    'Resources': 'Resources',
    'Overview': 'Overview',
    'Stories of impact': 'Stories of impact',
    'Publications': 'Publications',
    'Softgels': 'Softgels',
    'Tablets': 'Tablets',
    'Creams & Ointments': 'Creams & Ointments',
    'Injections': 'Injections',
  },
  pt: {
    'What science can do': 'O que a ciência pode fazer',
    'Home': 'Início',
    'About Us': 'Sobre nós',
    'Manufacturing': 'Fabricação',
    'R&D Innovation': 'R&D Innovation',
    'Quality & Compliance': 'Quality & Compliance',
    'Products': 'Products',
    'News': 'News',
    'Careers': 'Careers',
    'Contact': 'Contact',
    'Resources': 'Resources',
    'Overview': 'Overview',
    'Stories of impact': 'Stories of impact',
    'Publications': 'Publications',
    'Softgels': 'Softgels',
    'Tablets': 'Tablets',
    'Creams & Ointments': 'Creams & Ointments',
    'Injections': 'Injections',
  },
}

export function getNavLabel(key: string, locale: string = 'en'): string {
  return navTranslations[locale]?.[key] || navTranslations['en']?.[key] || key
}

export { navTranslations }

export const navigationConfig: NavigationConfig = {
  items: [
    { 
      label: 'What science can do', 
      href: '/what-science-can-do',
      hasDropdown: true,
      items: [
        { label: 'Overview', href: '/what-science-can-do' },
        { label: 'Stories of impact', href: '/what-science-can-do/stories-of-impact' },
        { label: 'Publications', href: '/what-science-can-do/publications' },
      ]
    },
    { label: 'Home', href: '/' },
    { label: 'About Us', href: '/about' },
    { label: 'Manufacturing', href: '/manufacturing' },
    { label: 'R&D Innovation', href: '/rd-innovation' },
    { label: 'Quality & Compliance', href: '/quality-compliance' },
    { 
      label: 'Products', 
      href: '/products', 
      hasDropdown: true,
      items: [
        { label: 'Overview', href: '/products' },
        { label: 'Softgels', href: '/products?category=softgels' },
        { label: 'Tablets', href: '/products?category=tablets' },
        { label: 'Creams & Ointments', href: '/products?category=creams' },
        { label: 'Injections', href: '/products?category=injections' },
      ]
    },
    { label: 'News', href: '/news' },
    { label: 'Careers', href: '/careers' },
    { label: 'Contact', href: '/contact' },
    { label: 'Resources', href: '/resources' },
  ],
  ctaButtons: {
    verify: { label: 'Verify', href: '/verify' },
    orderNow: { label: 'Order Now', href: '/order-now' },
    aiAssistant: { label: 'AI Assistant', href: '/ai-assistant' },
  },
  language: {
    default: 'en',
    options: [
      { code: 'en', label: 'English' },
      { code: 'lo', label: 'Lao' },
      { code: 'th', label: 'Thai' },
      { code: 'vi', label: 'Vietnamese' },
      { code: 'ar', label: 'Arabic' },
      { code: 'es', label: 'Spanish' },
      { code: 'pt', label: 'Portuguese' },
    ]
  }
}

export const whatScienceMenuItems: WhatScienceMenuItem[] = [
  { 
    label: 'What science can do', 
    href: '/what-science-can-do',
    description: 'Exploring the frontiers of pharmaceutical science and innovation'
  },
  { 
    label: 'Stories of impact', 
    href: '/what-science-can-do/stories-of-impact',
    description: 'Real-world impact of our research and partnerships'
  },
  { 
    label: 'Publications', 
    href: '/what-science-can-do/publications',
    description: 'Scientific publications, research papers and findings'
  },
]
